name: Build and Deploy to Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Node.js (LTS)
        uses: actions/setup-node@v6
        with:
          node-version: "lts/-2"
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Compile OpenSCAD Playground
        run: npm run build:all

      - name: Setup GitHub Pages Environment
        uses: actions/configure-pages@v5

      - name: Upload Production Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages Live Server
        id: deployment
        uses: actions/deploy-pages@v4