name: Test Build and Deploy

on:
  push:
    branches: [ "main" ] # Only deploys when you push to main
  workflow_dispatch:

# Grant permissions required for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/-2' # Uses the stable LTS version

      - name: Install Dependencies
        run: npm install

      - name: Compile Application Assets
        run: npm run build:all

      - name: Merge Public Assets and Compiled Code
        run: |
          mkdir -p dist_site
          cp -R public/* dist_site/
          cp -R dist/* dist_site/

      - name: Setup Pages Settings
        uses: actions/configure-pages@v4

      - name: Upload Pages Deployment Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist_site' # Instructs GitHub to deploy the merged folder

      - name: Deploy to GitHub Pages Live Site
        uses: actions/deploy-pages@v4